package problems.projecteuler.problem.difficulty_20;

import java.util.ArrayList;
import java.util.List;
import problems.projecteuler.problem.Problem;
import problems.projecteuler.util.ProjectEulerMath;

/**
 * @author lalalaflow
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * Anser : 4613732
 *
 * **tip : every third Fibonacci number is even.
 */
public class Problem2 implements Problem {
    int limitNum = 0;
    public Problem2() {
        this(4000000);
    }
    public Problem2(int limitNum){
        this.limitNum = limitNum;
    }

    public void solve() {

        System.out.println("The sum of the even-valued terms : "
                + this.sumEvenFibonacciSequence(this.findEvenFibonacciSequence(this.limitNum)));
    }

    /**
     * Find even fibonacci terms
     * @param limitNum
     * @return
     */
    private List<Integer> findEvenFibonacciSequence(int limitNum) {
        ArrayList<Integer> evenFibonacciSequences = new ArrayList<Integer>();
        int value1 = 0;
        int nextTerm;
        for(int value2 = 1; value2 <= limitNum; value2 = nextTerm) {
            if(this.ifEvenValue(value2)) {
                evenFibonacciSequences.add(Integer.valueOf(value2));
            }

            nextTerm = this.getNextTerm(value1, value2);
            value1 = value2;
        }

        return evenFibonacciSequences;
    }

    /**
     * Get next Fibonacci term
     * @param value1
     * @param value2
     * @return
     */
    private int getNextTerm(int value1, int value2) {

        return (value1 + value2);
    }

    /**
     * Check weather the number is Finobacci or not.
     * @param num
     * @return
     */
    private boolean ifEvenValue(int num) {

        return ProjectEulerMath.mod(num, 2) == 0;
    }

    /**
     * Sum the even Fibonacci terms in array.
     * @param evenFibonacciSequences
     * @return
     */
    private int sumEvenFibonacciSequence(List<Integer> evenFibonacciSequences) {
        int sum = 0;

        for(Integer i : evenFibonacciSequences) {
            sum += i.intValue();
        }

        return sum;
    }
}
